# Generated by Django 3.2.5 on 2022-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, default='HR.png', null=True, upload_to='')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('position', models.CharField(choices=[('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('Trainee', 'Trainee'), ('Network Support Specialist', 'Network Support Specialist'), ('System Analyst', 'System Analyst'), ('User Experience Designer', 'User Experience Designer'), ('Data Scientist', 'Data Scientist'), ('Database Administrator', 'Database Administrator')], max_length=50, null=True)),
                ('emp_type', models.CharField(choices=[('Seasonal', 'Seasonal'), ('Full-Time', 'Full-Time'), ('Part-time', 'Part-time'), ('Temporary', 'Temporary')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Terminated', 'Terminated'), ('Suspended', 'Suspended'), ('Active', 'Active'), ('On-Leave', 'On-Leave')], max_length=20, null=True)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
