# Generated by Django 3.2.5 on 2022-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Temporary', 'Temporary'), ('Part-time', 'Part-time'), ('Full-Time', 'Full-Time'), ('Seasonal', 'Seasonal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Suspended', 'Suspended'), ('On-Leave', 'On-Leave'), ('Active', 'Active'), ('Terminated', 'Terminated')], max_length=20, null=True),
        ),
    ]
