# Generated by Django 3.2.5 on 2022-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220727_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Seasonal', 'Seasonal'), ('Full-Time', 'Full-Time'), ('Part-time', 'Part-time'), ('Temporary', 'Temporary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Terminated', 'Terminated'), ('Suspended', 'Suspended'), ('On-Leave', 'On-Leave'), ('Active', 'Active')], max_length=20, null=True),
        ),
    ]
