# Generated by Django 3.2.5 on 2022-07-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220727_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_type',
            field=models.CharField(choices=[('Seasonal', 'Seasonal'), ('Part-time', 'Part-time'), ('Temporary', 'Temporary'), ('Full-Time', 'Full-Time')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Active', 'Active'), ('On-Leave', 'On-Leave')], max_length=20, null=True),
        ),
    ]
